name: github-actions
on: [push]
jobs:
  github-actions-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: make install
      - name: Run ESLint
        run: make lint-fix
